AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  detectVPC:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-detectVPC
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: detectVPC
      CodeUri: src/detectVPC
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSConfigRole
        - AmazonVPCFullAccess
        - SESCrudPolicy:
            IdentityName: !Ref EnvConfigvpcEmailAsString
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(0 16 * * ? *)
          Metadata:
            StackeryName: DailyChecker
      Environment:
        Variables:
          VPC_EMAIL: !Ref EnvConfigvpcEmailAsString
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvConfigvpcEmailAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/vpcEmail
Metadata:
  EnvConfigParameters:
    EnvConfigvpcEmailAsString: vpcEmail